Update detailed_weather.yml

diff --git a/.github/workflows/detailed_weather.yml b/.github/workflows/detailed_weather.yml
--- a/.github/workflows/detailed_weather.yml
+++ b/.github/workflows/detailed_weather.yml
@@ -35,12 +35,22 @@ jobs:
       - name: Get current date
         id: current_date
         run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
-        
+
+      - name: Debug secret presence
+        run: |
+          if [ -z "${{ secrets.WEATHER_API_KEY }}" ]; then
+            echo "❌ WEATHER_API_KEY is missing!"
+            exit 1
+          else
+            echo "✅ WEATHER_API_KEY is set"
+          fi
+          
       # Fetch data from your API
       - name: Fetch Marine API data
         run: |
           echo ${{ secrets.WEATHER_API_KEY }}
-          curl -X GET http://api.weatherapi.com/v1/marine.json?q=22.5744,88.3629&days=3&key=${{ secrets.WEATHER_API_KEY }} -o tmp/marine_weather_response.json
+          curl -X GET http://api.weatherapi.com/v1/marine.json?q=22.5744,88.3629&days=3&key=${{ secrets.WEATHER_API_KEY }} \
+              -o tmp/marine_weather_response.json
           
       - name: Fetch Astronomy API data
         run: |
